In [1]:
import pandas as pd

In [2]:
at = pd.read_csv("D:/Projetcs/Hospital Management System/appointments.csv")
bg = pd.read_csv("D:/Projetcs/Hospital Management System/billing.csv")
dt = pd.read_csv("D:/Projetcs/Hospital Management System/doctors.csv")
pt = pd.read_csv("D:/Projetcs/Hospital Management System/patients.csv")
tt = pd.read_csv("D:/Projetcs/Hospital Management System/treatments.csv")

In [3]:
at.head()

,appointment_id,patient_id,doctor_id,appointment_date,appointment_time,reason_for_visit,status
0,A001,P034,D009,2023-08-09,15:15:00,Therapy,Scheduled
1,A002,P032,D004,2023-06-09,14:30:00,Therapy,No-show
2,A003,P048,D004,2023-06-28,8:00:00,Consultation,Cancelled
3,A004,P025,D006,2023-09-01,9:15:00,Consultation,Cancelled
4,A005,P040,D003,2023-07-06,12:45:00,Emergency,No-show

In [4]:
at['appointment_date'] = pd.to_datetime(at['appointment_date'], format='%Y-%m-%d')
at['appointment_time'] = pd.to_datetime(at['appointment_time'], format ='%H:%M:%S').dt.time

In [5]:
bg.head()

,bill_id,patient_id,treatment_id,bill_date,amount,payment_method,payment_status
0,B001,P034,T001,2023-08-09,3941.97,Insurance,Pending
1,B002,P032,T002,2023-06-09,4158.44,Insurance,Paid
2,B003,P048,T003,2023-06-28,3731.55,Insurance,Paid
3,B004,P025,T004,2023-09-01,4799.86,Insurance,Failed
4,B005,P040,T005,2023-07-06,582.05,Credit Card,Pending

In [6]:
bg['bill_date'] = pd.to_datetime(bg['bill_date'])

In [7]:
dt.head()

,doctor_id,first_name,last_name,specialization,phone_number,years_experience,hospital_branch,email
0,D001,David,Taylor,Dermatology,8322010158,17.0,Westside Clinic,dr.david.taylor@hospital.com
1,D002,Jane,Davis,Pediatrics,9004382050,24.0,Eastside Clinic,dr.jane.davis@hospital.com
2,D003,Jane,Smith,Pediatrics,8737740598,19.0,Eastside Clinic,dr.jane.smith@hospital.com
3,D004,David,Jones,Pediatrics,6594221991,NaN,Central Hospital,dr.david.jones@hospital.com
4,D005,Sarah,Taylor,Dermatology,9118538547,26.0,Central Hospital,dr.sarah.taylor@hospital.com

In [8]:
pt.head()

,patient_id,first_name,last_name,gender,date_of_birth,contact_number,address,registration_date,insurance_provider,insurance_number,email
0,P001,David,Williams,F,04-06-1955,6939585183,789 Pine Rd,23-06-2022,WellnessCorp,INS840674,david.williams@mail.com
1,P002,Emily,Smith,F,12-10-1984,8228188767,321 Maple Dr,15-01-2022,PulseSecure,INS354079,emily.smith@mail.com
2,P003,Laura,Jones,M,21-08-1977,8397029847,321 Maple Dr,07-02-2022,PulseSecure,INS650929,laura.jones@mail.com
3,P004,Michael,Johnson,NaN,20-02-1981,9019443432,123 Elm St,02-03-2021,HealthIndia,INS789944,michael.johnson@mail.com
4,P005,David,Wilson,M,23-06-1960,7734463155,123 Elm St,29-09-2021,MedCare Plus,INS788105,david.wilson@mail.com

In [9]:
pt['date_of_birth'] = pd.to_datetime(pt['date_of_birth'], format = '%d-%m-%Y')
pt['registration_date'] = pd.to_datetime(pt['registration_date'], format = '%d-%m-%Y')

In [10]:
tt.head()

,treatment_id,appointment_id,treatment_type,description,cost,treatment_date
0,T001,A001,Chemotherapy,Basic screening,3941.97,09-08-2023
1,T002,A002,MRI,Advanced protocol,4158.44,09-06-2023
2,T003,A003,MRI,Standard procedure,3731.55,28-06-2023
3,T004,A004,MRI,Basic screening,4799.86,01-09-2023
4,T005,A005,ECG,Standard procedure,582.05,06-07-2023

In [11]:
tt['treatment_date'] = pd.to_datetime(tt['treatment_date'], format= '%d-%m-%Y')

In [12]:
at.info()
bg.info()
dt.info()
pt.info()
tt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   appointment_id    200 non-null    object
 1   patient_id        200 non-null    object
 2   doctor_id         200 non-null    object
 3   appointment_date  200 non-null    datetime64[ns]
 4   appointment_time  200 non-null    object
 5   reason_for_visit  200 non-null    object
 6   status            200 non-null    object
dtypes: datetime64[ns](1), object(6)
memory usage: 11.1+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   bill_id         200 non-null    object
 1   patient_id      200 non-null    object
 2   treatment_id    200 non-null    object
 3   bill_date       200 non-null    datetime64[ns]
 4   amount          200 non-null    float64
 5   payment_method  200 non-null    object
 6   payment_status  200 non-null    object
dtypes: datetime64[ns](1), float64(1), object(5)
memory usage: 11.1+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   doctor_id         10 non-null     object
 1   first_name        10 non-null     object
 2   last_name         10 non-null     object
 3   specialization    10 non-null     object
 4   phone_number      10 non-null     int64
 5   years_experience  8 non-null      float64
 6   hospital_branch   10 non-null     object
 7   email             10 non-null     object
dtypes: float64(1), int64(1), object(6)
memory usage: 772.0+ bytes
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   patient_id          50 non-null     object
 1   first_name          50 non-null     object
 2   last_name           50 non-null     object
 3   gender              45 non-null     object
 4   date_of_birth       50 non-null     datetime64[ns]
 5   contact_number      50 non-null     int64
 6   address             50 non-null     object
 7   registration_date   50 non-null     datetime64[ns]
 8   insurance_provider  50 non-null     object
 9   insurance_number    50 non-null     object
 10  email               50 non-null     object
dtypes: datetime64[ns](2), int64(1), object(8)
memory usage: 4.4+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   treatment_id    200 non-null    object
 1   appointment_id  200 non-null    object
 2   treatment_type  200 non-null    object
 3   description     200 non-null    object
 4   cost            188 non-null    float64
 5   treatment_date  200 non-null    datetime64[ns]
dtypes: datetime64[ns](1), float64(1), object(4)
memory usage: 9.5+ KB

In [13]:
tt.describe()

              cost       treatment_date
count   188.000000                  200
mean   2730.756755  2023-06-17 11:38:24
min     534.030000  2023-01-01 00:00:00
25%    1549.715000  2023-03-27 18:00:00
50%    2748.945000  2023-06-10 00:00:00
75%    3899.722500  2023-09-15 12:00:00
max    4973.630000  2023-12-30 00:00:00
std    1303.721703                  NaN

In [14]:
at.isnull().sum()

appointment_id      0
patient_id          0
doctor_id           0
appointment_date    0
appointment_time    0
reason_for_visit    0
status              0
dtype: int64

In [15]:
bg.isnull().sum()

bill_id           0
patient_id        0
treatment_id      0
bill_date         0
amount            0
payment_method    0
payment_status    0
dtype: int64

In [16]:
dt.isnull().sum()

doctor_id           0
first_name          0
last_name           0
specialization      0
phone_number        0
years_experience    2
hospital_branch     0
email               0
dtype: int64

In [17]:
pt.isnull().sum()

patient_id            0
first_name            0
last_name             0
gender                5
date_of_birth         0
contact_number        0
address               0
registration_date     0
insurance_provider    0
insurance_number      0
email                 0
dtype: int64

In [18]:
tt.isnull().sum()

treatment_id       0
appointment_id     0
treatment_type     0
description        0
cost              12
treatment_date     0
dtype: int64

In [19]:
dt['years_experience'].fillna(dt['years_experience'].mean(), inplace= True)
pt['gender'].fillna(pt['gender'].mode()[0], inplace = True)
tt['cost'] = tt.groupby('treatment_type')['cost'].transform(lambda x : x.fillna(x.mean()))

C:\Users\sahil\AppData\Local\Temp\ipykernel_18256\2367496188.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dt['years_experience'].fillna(dt['years_experience'].mean(), inplace= True)
C:\Users\sahil\AppData\Local\Temp\ipykernel_18256\2367496188.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  pt['gender'].fillna(pt['gender'].mode()[0], inplace = True)

In [20]:
dt.head()

,doctor_id,first_name,last_name,specialization,phone_number,years_experience,hospital_branch,email
0,D001,David,Taylor,Dermatology,8322010158,17.00,Westside Clinic,dr.david.taylor@hospital.com
1,D002,Jane,Davis,Pediatrics,9004382050,24.00,Eastside Clinic,dr.jane.davis@hospital.com
2,D003,Jane,Smith,Pediatrics,8737740598,19.00,Eastside Clinic,dr.jane.smith@hospital.com
3,D004,David,Jones,Pediatrics,6594221991,22.75,Central Hospital,dr.david.jones@hospital.com
4,D005,Sarah,Taylor,Dermatology,9118538547,26.00,Central Hospital,dr.sarah.taylor@hospital.com

In [21]:
pt.head()

,patient_id,first_name,last_name,gender,date_of_birth,contact_number,address,registration_date,insurance_provider,insurance_number,email
0,P001,David,Williams,F,1955-06-04,6939585183,789 Pine Rd,2022-06-23,WellnessCorp,INS840674,david.williams@mail.com
1,P002,Emily,Smith,F,1984-10-12,8228188767,321 Maple Dr,2022-01-15,PulseSecure,INS354079,emily.smith@mail.com
2,P003,Laura,Jones,M,1977-08-21,8397029847,321 Maple Dr,2022-02-07,PulseSecure,INS650929,laura.jones@mail.com
3,P004,Michael,Johnson,M,1981-02-20,9019443432,123 Elm St,2021-03-02,HealthIndia,INS789944,michael.johnson@mail.com
4,P005,David,Wilson,M,1960-06-23,7734463155,123 Elm St,2021-09-29,MedCare Plus,INS788105,david.wilson@mail.com

In [22]:
tt.head()

,treatment_id,appointment_id,treatment_type,description,cost,treatment_date
0,T001,A001,Chemotherapy,Basic screening,3941.97,2023-08-09
1,T002,A002,MRI,Advanced protocol,4158.44,2023-06-09
2,T003,A003,MRI,Standard procedure,3731.55,2023-06-28
3,T004,A004,MRI,Basic screening,4799.86,2023-09-01
4,T005,A005,ECG,Standard procedure,582.05,2023-07-06

In [24]:
from sqlalchemy import create_engine

# Step 1: Connect to PostgreSQL
# Replace placeholders with your actual details
username = "postgres"      # default user
password = "Sankalp7*" # the password you set during installation
host = "localhost"         # if running locally
port = "5432"              # default PostgreSQL port
database = "hospital"    # the database you created in pgAdmin

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

# Step 2: Load DataFrame into PostgreSQL
tables = {
    "appointments" : at, 
    "billing" : bg,
    "doctors" : dt,
    "patients" : pt,
    "treatments" : tt
}  # choose any table name
for table_name, df in tables.items():
    df.to_sql(table_name, engine, if_exists="replace", index=False)
    print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

Data successfully loaded into table 'appointments' in database 'hospital'.
Data successfully loaded into table 'billing' in database 'hospital'.
Data successfully loaded into table 'doctors' in database 'hospital'.
Data successfully loaded into table 'patients' in database 'hospital'.
Data successfully loaded into table 'treatments' in database 'hospital'.